// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoS7GJwCdQK0a6b33-0TBWPGugKUMWWxQ',
    appId: '1:860995907155:web:0030431a9e5161ce86a0a6',
    messagingSenderId: '860995907155',
    projectId: 'myuas-ffa91',
    authDomain: 'myuas-ffa91.firebaseapp.com',
    storageBucket: 'myuas-ffa91.appspot.com',
    measurementId: 'G-S6B62Y4JJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXLIASHhwYWaBNZHiFFYWnxs0eondYJg',
    appId: '1:860995907155:android:b28b5d7c5c5b7b2c86a0a6',
    messagingSenderId: '860995907155',
    projectId: 'myuas-ffa91',
    storageBucket: 'myuas-ffa91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1vb8h0zhk8A4AQBI78Db5b63BZ8wL-g',
    appId: '1:860995907155:ios:177a36eb7ca2254286a0a6',
    messagingSenderId: '860995907155',
    projectId: 'myuas-ffa91',
    storageBucket: 'myuas-ffa91.appspot.com',
    iosClientId: '860995907155-7ur4dmr99t5de12rgakgcn3ne7m181u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1vb8h0zhk8A4AQBI78Db5b63BZ8wL-g',
    appId: '1:860995907155:ios:177a36eb7ca2254286a0a6',
    messagingSenderId: '860995907155',
    projectId: 'myuas-ffa91',
    storageBucket: 'myuas-ffa91.appspot.com',
    iosClientId: '860995907155-7ur4dmr99t5de12rgakgcn3ne7m181u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUas',
  );
}
